### ISSUE TITLE
What's the purpose of ArraySerializableInterface?

### ISSUE THREAD

**Issue by evpav** [zendframework/zend-stdlib#80]
Why it is not used internally, for ArrayObject for example?
Why its exchangeArray interface isn't compatible with both \ArrayObject and \Zend\Stdlib\ArrayObject?

**Comment by weierophinney** [comment]
It is used primarily by the zend-hydrator components, in order to allow array-like objects to indicate they are serializable. In most cases, we will check for one of either `ArrayObject` or `Zend\Stdlib\ArraySerializableInterface` in order to determine if we can use that strategy for de/serialization purposes.

In the future, please ask questions in either:

- [Chat](https://zendframework-slack.herokuapp.com)
- [Forums](https://discourse.zendframework.com)
